global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules

scrape_configs:
  - job_name: 'task-backend'
    static_configs:
      - targets: ['task-backend:8080']

  - job_name: 'rocketmq'
    static_configs:
      - targets: ['rocketmq-namesrv:9876']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo-exporter:9216']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra-exporter:8080']
