version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana:/etc/grafana/provisioning
