apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -staging

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: task-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
